import { Question } from './types';

export const AIML_TOPICS = [
  'Machine Learning Fundamentals',
  'Neural Networks & Deep Learning',
  'Supervised Learning',
  'Unsupervised Learning',
  'Model Evaluation & Optimization',
  'Natural Language Processing',
  'Computer Vision',
  'Reinforcement Learning',
];

export const AIML_QUESTIONS: Question[] = [
  // ── MACHINE LEARNING FUNDAMENTALS ───────────────────────────
  {
    id: 101,
    text: 'Which type of learning uses labelled training data to learn a mapping from inputs to outputs?',
    options: ['Unsupervised Learning', 'Reinforcement Learning', 'Supervised Learning', 'Self-supervised Learning'],
    correctAnswer: 2,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Easy',
    explanation: 'Supervised learning trains on (input, label) pairs to predict labels for unseen inputs.',
  },
  {
    id: 102,
    text: 'The "No Free Lunch" theorem states that:',
    options: [
      'Neural networks outperform all other models on any task',
      'No single algorithm performs best across all possible problems',
      'More data always improves model accuracy',
      'Regularisation always prevents overfitting',
    ],
    correctAnswer: 1,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Medium',
    explanation: 'No Free Lunch: averaged over all problems, no algorithm is universally superior to any other.',
  },
  {
    id: 103,
    text: 'Overfitting can be identified when:',
    options: [
      'Training loss is high and validation loss is high',
      'Training loss is low but validation loss is significantly higher',
      'Both training and validation loss decrease together',
      'The model predicts the same class for all inputs',
    ],
    correctAnswer: 1,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Easy',
    explanation: 'Overfitting: model memorises training data — low training error but high generalisation error.',
  },
  {
    id: 104,
    text: 'Which technique reduces overfitting by randomly setting neurons to zero during training?',
    options: ['Batch Normalisation', 'Weight Decay', 'Dropout', 'Early Stopping'],
    correctAnswer: 2,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Easy',
    explanation: 'Dropout randomly disables neurons each forward pass, preventing co-adaptation and acting as an ensemble.',
  },
  {
    id: 105,
    text: 'Bias in a model refers to:',
    options: [
      'Sensitivity to small fluctuations in training data',
      'Error from incorrect assumptions about the problem (underfitting)',
      'Error introduced by normalising features',
      'Difference between predicted and actual class labels',
    ],
    correctAnswer: 1,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Medium',
    explanation: 'High bias → model too simple, underfits. High variance → model too complex, overfits. The bias–variance tradeoff balances both.',
  },
  {
    id: 106,
    text: 'Feature scaling is important for which of the following algorithms?',
    options: ['Decision Trees', 'Random Forests', 'K-Nearest Neighbours (KNN)', 'Naive Bayes'],
    correctAnswer: 2,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Medium',
    explanation: 'KNN uses distance metrics; unscaled features with large ranges dominate distances. Trees split on thresholds and are scale-invariant.',
  },
  {
    id: 107,
    text: 'Which of the following is a parametric machine learning model?',
    options: ['K-Nearest Neighbours', 'Kernel SVM (RBF)', 'Logistic Regression', 'Random Forest'],
    correctAnswer: 2,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Hard',
    explanation: 'Parametric models (Linear/Logistic Regression) have a fixed number of parameters regardless of training-set size.',
  },
  {
    id: 108,
    text: 'Cross-validation is primarily used to:',
    options: [
      'Speed up model training',
      'Estimate model generalisation performance on unseen data',
      'Increase training dataset size',
      'Select the best loss function',
    ],
    correctAnswer: 1,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Medium',
    explanation: 'k-fold cross-validation partitions data into k folds, trains on k-1 and validates on 1, giving a robust generalisation estimate.',
  },

  // ── NEURAL NETWORKS & DEEP LEARNING ─────────────────────────
  {
    id: 109,
    text: 'The activation function that solves the vanishing gradient problem better than sigmoid/tanh is:',
    options: ['Sigmoid', 'Tanh', 'ReLU', 'Softmax'],
    correctAnswer: 2,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Easy',
    explanation: 'ReLU (max(0,x)) has a gradient of 1 for positive inputs, avoiding the near-zero gradients sigmoid/tanh produce for large inputs.',
  },
  {
    id: 110,
    text: 'Backpropagation computes gradients using:',
    options: ['Forward pass only', 'The chain rule of calculus', 'Numerical differentiation exclusively', 'Monte Carlo estimation'],
    correctAnswer: 1,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Easy',
    explanation: 'Backpropagation applies the chain rule repeatedly from output to input layers to compute ∂Loss/∂w for each weight.',
  },
  {
    id: 111,
    text: 'Batch Normalisation normalises activations:',
    options: [
      'Across all training examples simultaneously',
      'Per mini-batch, then applies learnable scale (γ) and shift (β)',
      'Using the test set statistics',
      'Only during inference, not training',
    ],
    correctAnswer: 1,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Medium',
    explanation: 'BatchNorm computes mean/variance over the current mini-batch, normalises, then rescales with learnable γ and β.',
  },
  {
    id: 112,
    text: 'In a Convolutional Neural Network, pooling layers are used to:',
    options: [
      'Increase the spatial resolution of feature maps',
      'Reduce spatial dimensions and provide spatial invariance',
      'Apply non-linearity to feature maps',
      'Initialise weights',
    ],
    correctAnswer: 1,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Easy',
    explanation: 'Max/Average Pooling downsamples feature maps, reducing parameters and providing translational invariance.',
  },
  {
    id: 113,
    text: 'The vanishing gradient problem is most severe in:',
    options: ['Shallow networks', 'Deep networks with sigmoid activations', 'CNNs with ReLU', 'Transformer models'],
    correctAnswer: 1,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Medium',
    explanation: 'Sigmoid saturates near 0/1 with near-zero derivatives; multiplying many of these across deep layers makes gradients vanish.',
  },
  {
    id: 114,
    text: 'ResNets (Residual Networks) introduce skip connections to solve:',
    options: ['Overfitting', 'Vanishing/degradation gradient problem in very deep networks', 'Slow inference', 'Large memory consumption'],
    correctAnswer: 1,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Medium',
    explanation: 'Skip connections allow gradients to flow directly through the identity shortcut, enabling training of 100+ layer networks.',
  },
  {
    id: 115,
    text: 'The Attention mechanism in Transformers computes:',
    options: [
      'Weighted average of value vectors using similarity between query and key vectors',
      'Element-wise product of input embeddings',
      'Convolution over token positions',
      'RNN hidden state updates',
    ],
    correctAnswer: 0,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Hard',
    explanation: 'Attention: softmax(QKᵀ/√dₖ)·V — similarities between queries and keys produce weights over values.',
  },
  {
    id: 116,
    text: 'What does the "depth" of a neural network refer to?',
    options: [
      'The number of neurons in the widest layer',
      'The number of layers (including hidden layers)',
      'The dimensionality of the input',
      'The number of training epochs',
    ],
    correctAnswer: 1,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Easy',
    explanation: "A network's depth = total number of layers with learnable parameters (excludes input layer by convention).",
  },

  // ── SUPERVISED LEARNING ──────────────────────────────────────
  {
    id: 117,
    text: 'Which algorithm builds an ensemble by training each new model on the residual errors of the previous ones?',
    options: ['Random Forest', 'Bagging', 'Gradient Boosting', 'AdaBoost'],
    correctAnswer: 2,
    category: 'Supervised Learning',
    difficulty: 'Medium',
    explanation: 'Gradient Boosting sequentially fits new trees to the negative gradient (pseudo-residuals) of the loss function.',
  },
  {
    id: 118,
    text: 'The decision boundary of a linear SVM is determined by:',
    options: [
      'All training points',
      'Only the support vectors (closest points to the margin)',
      'The centroid of each class',
      'The mean and variance of features',
    ],
    correctAnswer: 1,
    category: 'Supervised Learning',
    difficulty: 'Medium',
    explanation: 'SVM maximises the margin between classes; only the support vectors (points on the margin) define the hyperplane.',
  },
  {
    id: 119,
    text: 'Logistic Regression outputs:',
    options: [
      'A raw score between −∞ and +∞',
      'A probability between 0 and 1 via the sigmoid function',
      'A class index directly',
      'Distance from the decision boundary',
    ],
    correctAnswer: 1,
    category: 'Supervised Learning',
    difficulty: 'Easy',
    explanation: 'Logistic Regression applies σ(wᵀx + b) where σ is the sigmoid, squashing the linear score to (0, 1).',
  },
  {
    id: 120,
    text: 'Random Forest reduces variance compared to a single decision tree by:',
    options: [
      'Using deeper trees',
      'Averaging predictions of many decorrelated trees trained on bootstrapped data subsets',
      'Training on the full dataset multiple times',
      'Applying L2 regularisation to each tree',
    ],
    correctAnswer: 1,
    category: 'Supervised Learning',
    difficulty: 'Medium',
    explanation: 'Bagging + random feature selection decorrelates trees; averaging their predictions reduces variance without increasing bias much.',
  },
  {
    id: 121,
    text: 'The kernel trick in SVM allows:',
    options: [
      'Faster matrix operations',
      'Implicitly mapping inputs to a high-dimensional feature space without computing the mapping',
      'Training without labelled data',
      'Replacing the loss function with a kernel function',
    ],
    correctAnswer: 1,
    category: 'Supervised Learning',
    difficulty: 'Hard',
    explanation: 'The kernel K(xᵢ, xⱼ) = φ(xᵢ)·φ(xⱼ) computes the dot product in feature space without explicitly computing φ.',
  },
  {
    id: 122,
    text: 'In a decision tree, the Gini Impurity measures:',
    options: [
      'The depth of the tree',
      'The probability that a randomly chosen sample is misclassified if labelled according to class distribution',
      'Information gained after a split',
      'The number of leaf nodes',
    ],
    correctAnswer: 1,
    category: 'Supervised Learning',
    difficulty: 'Medium',
    explanation: 'Gini = 1 − Σpᵢ². Lower Gini at a node means a purer split (one class dominates).',
  },

  // ── UNSUPERVISED LEARNING ────────────────────────────────────
  {
    id: 123,
    text: 'K-Means clustering requires you to specify:',
    options: ['The cluster shapes', 'The number of clusters K upfront', 'The distance metric only', 'A labelled training set'],
    correctAnswer: 1,
    category: 'Unsupervised Learning',
    difficulty: 'Easy',
    explanation: 'K-Means initialises K centroids and iterates; K must be chosen before running the algorithm.',
  },
  {
    id: 124,
    text: 'Principal Component Analysis (PCA) finds:',
    options: [
      'The class boundaries in feature space',
      'Orthogonal directions (principal components) of maximum variance in the data',
      'Cluster centroids',
      'The most correlated feature pairs',
    ],
    correctAnswer: 1,
    category: 'Unsupervised Learning',
    difficulty: 'Medium',
    explanation: 'PCA projects data onto eigenvectors of the covariance matrix ordered by eigenvalue (variance explained).',
  },
  {
    id: 125,
    text: 'DBSCAN classifies points that do not belong to any cluster as:',
    options: ['Centroids', 'Core points', 'Noise/Outliers', 'Border points'],
    correctAnswer: 2,
    category: 'Unsupervised Learning',
    difficulty: 'Easy',
    explanation: 'DBSCAN labels sparse points that are not within ε of a core point as noise (outliers).',
  },
  {
    id: 126,
    text: 'An autoencoder is trained to:',
    options: [
      'Classify inputs into predefined categories',
      'Reconstruct its input at the output, learning a compressed latent representation',
      'Generate new images from random noise',
      'Rank inputs by similarity',
    ],
    correctAnswer: 1,
    category: 'Unsupervised Learning',
    difficulty: 'Medium',
    explanation: 'Autoencoder: encoder compresses input to a bottleneck latent code; decoder reconstructs the original. Loss = reconstruction error.',
  },
  {
    id: 127,
    text: 'The Elbow Method in K-Means is used to:',
    options: [
      'Select the learning rate',
      'Choose the optimal number of clusters K by finding the "elbow" in the inertia-vs-K plot',
      'Detect outliers in the dataset',
      'Initialise centroids optimally',
    ],
    correctAnswer: 1,
    category: 'Unsupervised Learning',
    difficulty: 'Medium',
    explanation: 'Plot within-cluster sum of squares (inertia) vs K; the "elbow" where marginal gain decreases sharply suggests the best K.',
  },
  {
    id: 128,
    text: 'Hierarchical clustering produces:',
    options: ['A flat partition of K clusters', 'A dendrogram showing nested cluster merges/splits', 'Cluster probabilities per sample', 'A single cluster'],
    correctAnswer: 1,
    category: 'Unsupervised Learning',
    difficulty: 'Medium',
    explanation: 'Hierarchical (agglomerative or divisive) clustering builds a tree (dendrogram) from which any K clusters can be cut.',
  },

  // ── MODEL EVALUATION & OPTIMIZATION ─────────────────────────
  {
    id: 129,
    text: 'The F1-Score is defined as:',
    options: [
      'Arithmetic mean of precision and recall',
      'Harmonic mean of precision and recall',
      'Geometric mean of precision and recall',
      'Difference between precision and recall',
    ],
    correctAnswer: 1,
    category: 'Model Evaluation & Optimization',
    difficulty: 'Easy',
    explanation: 'F1 = 2·(P·R)/(P+R) — the harmonic mean penalises extreme imbalance between precision and recall.',
  },
  {
    id: 130,
    text: 'ROC-AUC measures:',
    options: [
      'Accuracy at a single threshold',
      "The model's ability to discriminate between classes across all classification thresholds",
      'Training vs validation loss gap',
      'The number of false negatives',
    ],
    correctAnswer: 1,
    category: 'Model Evaluation & Optimization',
    difficulty: 'Medium',
    explanation: 'AUC = area under the ROC curve (TPR vs FPR at all thresholds). AUC = 0.5 is random; 1.0 is perfect.',
  },
  {
    id: 131,
    text: 'L1 regularisation (Lasso) tends to produce:',
    options: [
      'Models with many small weights',
      'Sparse models (many weights driven to exactly zero)',
      'The same result as L2 regularisation',
      'Faster convergence than L2',
    ],
    correctAnswer: 1,
    category: 'Model Evaluation & Optimization',
    difficulty: 'Medium',
    explanation: 'L1 penalty (Σ|wᵢ|) has a non-smooth origin that pushes weights exactly to zero, performing implicit feature selection.',
  },
  {
    id: 132,
    text: 'In stochastic gradient descent (SGD), parameters are updated:',
    options: [
      'After computing gradients over the full dataset',
      'After computing gradients over a single (or small mini-batch of) training example(s)',
      'Only at the end of each epoch',
      'Using second-order derivatives',
    ],
    correctAnswer: 1,
    category: 'Model Evaluation & Optimization',
    difficulty: 'Easy',
    explanation: 'SGD updates weights after each example (or mini-batch), providing noisy but frequent updates that often escape local minima.',
  },
  {
    id: 133,
    text: 'The Adam optimiser combines:',
    options: [
      'SGD and Nesterov momentum',
      'Momentum (first moment) and RMSProp (second moment) adaptive learning rates',
      'L1 and L2 regularisation',
      'Gradient clipping and weight decay',
    ],
    correctAnswer: 1,
    category: 'Model Evaluation & Optimization',
    difficulty: 'Hard',
    explanation: 'Adam maintains per-parameter first moment (mean) and second moment (uncentred variance) estimates for adaptive step sizes.',
  },
  {
    id: 134,
    text: 'Precision is defined as:',
    options: [
      'TP / (TP + FN)',
      'TP / (TP + FP)',
      '(TP + TN) / Total',
      'TN / (TN + FP)',
    ],
    correctAnswer: 1,
    category: 'Model Evaluation & Optimization',
    difficulty: 'Easy',
    explanation: 'Precision = TP / (TP + FP) — out of all predicted positives, how many were actually positive.',
  },

  // ── NATURAL LANGUAGE PROCESSING ──────────────────────────────
  {
    id: 135,
    text: 'TF-IDF stands for:',
    options: [
      'Term Frequency–Inverse Document Frequency',
      'Token Frequency–Inverse Data Fraction',
      'Text Feature–Index Data Function',
      'Term Feature–Inverted Dictionary Format',
    ],
    correctAnswer: 0,
    category: 'Natural Language Processing',
    difficulty: 'Easy',
    explanation: 'TF-IDF weights terms high when frequent in a document (TF) but rare across all documents (IDF), highlighting distinctive words.',
  },
  {
    id: 136,
    text: 'Word2Vec trains word embeddings by:',
    options: [
      'Predicting word frequency from document length',
      'Predicting a word from its context (CBOW) or context from a word (Skip-gram)',
      'Computing co-occurrence matrices with SVD',
      'Clustering words by syntactic category',
    ],
    correctAnswer: 1,
    category: 'Natural Language Processing',
    difficulty: 'Medium',
    explanation: 'Word2Vec uses shallow neural nets: CBOW predicts a word from surrounding context; Skip-gram predicts context from a word.',
  },
  {
    id: 137,
    text: 'BERT (Bidirectional Encoder Representations from Transformers) is pre-trained using:',
    options: [
      'Next-sentence prediction only',
      'Masked Language Modelling (MLM) and Next Sentence Prediction (NSP)',
      'Left-to-right language modelling like GPT',
      'Contrastive learning on image-text pairs',
    ],
    correctAnswer: 1,
    category: 'Natural Language Processing',
    difficulty: 'Hard',
    explanation: 'BERT masks ~15% of tokens (MLM) and classifies whether two sentences are consecutive (NSP), enabling bidirectional context.',
  },
  {
    id: 138,
    text: 'Tokenisation in NLP refers to:',
    options: [
      'Converting numerical features to tokens',
      'Splitting raw text into smaller units (words, subwords, or characters)',
      'Encrypting text data',
      'Mapping words to their POS tags',
    ],
    correctAnswer: 1,
    category: 'Natural Language Processing',
    difficulty: 'Easy',
    explanation: 'Tokenisation breaks text into tokens — the atomic units fed to an NLP model (e.g., BPE subword tokens for modern LLMs).',
  },

  // ── COMPUTER VISION ──────────────────────────────────────────
  {
    id: 139,
    text: 'In a CNN, the receptive field refers to:',
    options: [
      'Number of filters in the last layer',
      'The region of the input image that influences a particular neuron\'s output',
      'Stride applied during pooling',
      'Total number of trainable parameters',
    ],
    correctAnswer: 1,
    category: 'Computer Vision',
    difficulty: 'Medium',
    explanation: 'Receptive field grows with depth; deeper neurons "see" larger portions of the input due to stacked convolutions.',
  },
  {
    id: 140,
    text: 'Data augmentation in computer vision is used to:',
    options: [
      'Reduce model inference time',
      'Artificially increase training set diversity and reduce overfitting',
      'Speed up convolutional operations',
      'Normalise pixel values',
    ],
    correctAnswer: 1,
    category: 'Computer Vision',
    difficulty: 'Easy',
    explanation: 'Techniques like flipping, cropping, colour jitter, and rotation create varied versions of training images, improving generalisation.',
  },
  {
    id: 141,
    text: 'Transfer learning in computer vision typically involves:',
    options: [
      'Training a model from scratch on the target dataset',
      'Taking a pre-trained model (e.g., ImageNet) and fine-tuning it on a new task',
      'Copying weights without updating them',
      'Using the target model to label data for the source task',
    ],
    correctAnswer: 1,
    category: 'Computer Vision',
    difficulty: 'Medium',
    explanation: 'Pre-trained CNNs (ResNet, EfficientNet) on ImageNet have reusable low-level features; fine-tuning adapts higher layers to new tasks.',
  },

  // ── REINFORCEMENT LEARNING ───────────────────────────────────
  {
    id: 142,
    text: 'In reinforcement learning, an agent learns by:',
    options: [
      'Minimising a supervised loss function',
      'Interacting with an environment and maximising cumulative reward',
      'Clustering unlabelled states',
      'Copying demonstrations from an expert policy',
    ],
    correctAnswer: 1,
    category: 'Reinforcement Learning',
    difficulty: 'Easy',
    explanation: 'RL: agent observes state, takes action, receives reward/next-state, and updates its policy to maximise long-run return.',
  },
  {
    id: 143,
    text: 'The Bellman Equation defines the value of a state as:',
    options: [
      'Expected immediate reward only',
      'Immediate reward plus discounted value of the next state under the current policy',
      'The maximum reward achievable from that state',
      'The probability of reaching a terminal state',
    ],
    correctAnswer: 1,
    category: 'Reinforcement Learning',
    difficulty: 'Medium',
    explanation: 'V(s) = R(s,a) + γ·V(s\') — the Bellman equation decomposes the value into reward now + future value discounted by γ.',
  },
  {
    id: 144,
    text: 'Q-Learning is classified as:',
    options: [
      'Model-based, on-policy',
      'Model-free, off-policy',
      'Model-based, off-policy',
      'Model-free, on-policy',
    ],
    correctAnswer: 1,
    category: 'Reinforcement Learning',
    difficulty: 'Hard',
    explanation: 'Q-Learning is model-free (no environment model) and off-policy (learns optimal Q regardless of behaviour policy).',
  },
  {
    id: 145,
    text: 'The exploration–exploitation trade-off in RL is managed by strategies such as:',
    options: [
      'Gradient clipping',
      'ε-greedy: choose random action with probability ε, else greedy',
      'Dropout',
      'Batch normalisation of rewards',
    ],
    correctAnswer: 1,
    category: 'Reinforcement Learning',
    difficulty: 'Medium',
    explanation: 'ε-greedy balances exploring new actions (random) vs exploiting known good actions (greedy), with ε decayed over time.',
  },
  {
    id: 146,
    text: 'In Deep Q-Networks (DQN), a target network is used to:',
    options: [
      'Increase exploration',
      'Stabilise training by providing slowly updated, fixed Q-value targets',
      'Reduce memory requirements',
      'Replace experience replay',
    ],
    correctAnswer: 1,
    category: 'Reinforcement Learning',
    difficulty: 'Hard',
    explanation: 'Without a target network, Q-targets shift constantly during training causing instability. The target net is updated only every N steps.',
  },
  {
    id: 147,
    text: 'Which of the following is a policy-gradient method?',
    options: ['Q-Learning', 'SARSA', 'REINFORCE', 'Value Iteration'],
    correctAnswer: 2,
    category: 'Reinforcement Learning',
    difficulty: 'Hard',
    explanation: 'REINFORCE directly optimises the policy by computing ∇log π(a|s)·G, adjusting action probabilities proportional to return.',
  },

  // ── ADDITIONAL CROSS-TOPIC QUESTIONS ────────────────────────
  {
    id: 148,
    text: 'Generative Adversarial Networks (GANs) consist of:',
    options: [
      'An encoder and decoder network',
      'A generator and a discriminator trained in an adversarial min-max game',
      'Two classifiers competing for accuracy',
      'A sequence-to-sequence model with attention',
    ],
    correctAnswer: 1,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Medium',
    explanation: 'GAN: generator tries to fool the discriminator; discriminator tries to distinguish real from fake. The game drives the generator toward realistic outputs.',
  },
  {
    id: 149,
    text: 'The curse of dimensionality refers to:',
    options: [
      'Slow training due to high GPU memory usage',
      'The exponential increase in volume as dimensions grow, making data sparse and distance metrics less meaningful',
      'Overfitting caused by too many layers',
      'High computational cost of matrix multiplication',
    ],
    correctAnswer: 1,
    category: 'Machine Learning Fundamentals',
    difficulty: 'Hard',
    explanation: 'In high dimensions, data becomes sparse, distances lose contrast, and models require exponentially more data to generalise well.',
  },
  {
    id: 150,
    text: 'Which loss function is used for multi-class classification in neural networks?',
    options: ['Mean Squared Error', 'Binary Cross-Entropy', 'Categorical Cross-Entropy', 'Hinge Loss'],
    correctAnswer: 2,
    category: 'Neural Networks & Deep Learning',
    difficulty: 'Easy',
    explanation: 'Categorical Cross-Entropy: −Σ yᵢ log(ŷᵢ) over C classes, paired with a softmax output layer for multi-class problems.',
  },
];
