import { Question } from './types';

export const OS_TOPICS = [
  'CPU Scheduling',
  'Memory Management',
  'Page Replacement',
  'Deadlocks',
  'Process Synchronization',
  'File Systems',
  'Threads & Concurrency',
  'Virtual Memory',
];

export const OS_QUESTIONS: Question[] = [
  // ── CPU SCHEDULING ──────────────────────────────────────────
  {
    id: 1,
    text: 'Which scheduling algorithm assigns the CPU to the process with the smallest next CPU burst?',
    options: ['FCFS', 'Shortest Job First (SJF)', 'Round Robin', 'Priority Scheduling'],
    correctAnswer: 1,
    category: 'CPU Scheduling',
    difficulty: 'Easy',
    explanation: 'SJF selects the process whose next CPU burst is the shortest, minimizing average waiting time.',
  },
  {
    id: 2,
    text: 'Which CPU scheduling algorithm suffers from the "Convoy Effect"?',
    options: ['SJF', 'Round Robin', 'FCFS', 'Multilevel Queue'],
    correctAnswer: 2,
    category: 'CPU Scheduling',
    difficulty: 'Easy',
    explanation: 'In FCFS, a long-running process holds the CPU while shorter processes queue behind it — the convoy effect.',
  },
  {
    id: 3,
    text: 'In Round Robin scheduling, if the time quantum is very large, the algorithm behaves like:',
    options: ['SJF', 'FCFS', 'Priority Scheduling', 'Multilevel Feedback Queue'],
    correctAnswer: 1,
    category: 'CPU Scheduling',
    difficulty: 'Medium',
    explanation: 'When the quantum is larger than the longest burst time, every process runs to completion in order — identical to FCFS.',
  },
  {
    id: 4,
    text: 'Which of the following is a preemptive version of SJF?',
    options: ['FCFS', 'Shortest Remaining Time First (SRTF)', 'Round Robin', 'Priority (non-preemptive)'],
    correctAnswer: 1,
    category: 'CPU Scheduling',
    difficulty: 'Medium',
    explanation: 'SRTF preempts the running process if a newly arrived process has a shorter remaining burst time.',
  },
  {
    id: 5,
    text: 'Starvation in priority scheduling is best solved by:',
    options: ['Increasing time quantum', 'Aging', 'FCFS fallback', 'Reducing context-switch overhead'],
    correctAnswer: 1,
    category: 'CPU Scheduling',
    difficulty: 'Medium',
    explanation: 'Aging gradually increases the priority of waiting processes so they eventually get scheduled.',
  },
  {
    id: 6,
    text: 'Which metric measures the ratio of CPU burst time to total time in the system?',
    options: ['Throughput', 'CPU Utilization', 'CPU Efficiency Ratio', 'Turnaround Time'],
    correctAnswer: 2,
    category: 'CPU Scheduling',
    difficulty: 'Hard',
    explanation: 'CPU Efficiency Ratio = burst time / (burst time + waiting time). High ratio means low overhead.',
  },
  {
    id: 7,
    text: 'In Multilevel Feedback Queue (MLFQ), a process that uses too much CPU time is:',
    options: ['Terminated', 'Moved to a lower-priority queue', 'Moved to a higher-priority queue', 'Frozen until next cycle'],
    correctAnswer: 1,
    category: 'CPU Scheduling',
    difficulty: 'Hard',
    explanation: 'MLFQ demotes CPU-intensive processes to lower queues, favouring short interactive bursts.',
  },
  {
    id: 8,
    text: 'For n processes with the same arrival time, which algorithm gives the minimum average waiting time?',
    options: ['FCFS', 'Round Robin (quantum=1)', 'SJF', 'Priority Scheduling'],
    correctAnswer: 2,
    category: 'CPU Scheduling',
    difficulty: 'Medium',
    explanation: 'SJF is provably optimal for minimising average waiting time when all processes arrive simultaneously.',
  },

  // ── MEMORY MANAGEMENT ───────────────────────────────────────
  {
    id: 9,
    text: 'Internal fragmentation occurs in which memory allocation technique?',
    options: ['Segmentation', 'Dynamic partitioning', 'Fixed-size partitioning (paging)', 'Linked allocation'],
    correctAnswer: 2,
    category: 'Memory Management',
    difficulty: 'Easy',
    explanation: 'Fixed partitions assign a fixed block; unused space inside the block is internal fragmentation.',
  },
  {
    id: 10,
    text: 'Which memory allocation strategy tends to leave the smallest leftover holes?',
    options: ['First Fit', 'Best Fit', 'Worst Fit', 'Next Fit'],
    correctAnswer: 1,
    category: 'Memory Management',
    difficulty: 'Easy',
    explanation: 'Best Fit searches for the smallest hole that is large enough, leaving the least wasted space.',
  },
  {
    id: 11,
    text: 'Compaction is a technique used to solve:',
    options: ['Internal fragmentation', 'External fragmentation', 'Page faults', 'Thrashing'],
    correctAnswer: 1,
    category: 'Memory Management',
    difficulty: 'Easy',
    explanation: 'Compaction shuffles memory contents to consolidate free holes into one large block, fixing external fragmentation.',
  },
  {
    id: 12,
    text: 'In a paging system, the page table is stored in:',
    options: ['CPU registers only', 'Main memory (RAM)', 'Secondary storage', 'Cache exclusively'],
    correctAnswer: 1,
    category: 'Memory Management',
    difficulty: 'Medium',
    explanation: 'The page table lives in RAM; PTBR (Page Table Base Register) points to its starting address.',
  },
  {
    id: 13,
    text: 'A TLB (Translation Lookaside Buffer) is used to:',
    options: [
      'Store frequently used pages in swap',
      'Cache recent page-table translations to speed up address translation',
      'Replace the page table entirely',
      'Handle disk I/O interrupts',
    ],
    correctAnswer: 1,
    category: 'Memory Management',
    difficulty: 'Medium',
    explanation: 'TLB is a fast hardware cache for virtual-to-physical address mappings, reducing memory accesses per translation.',
  },
  {
    id: 14,
    text: 'What is the effective access time (EAT) formula when TLB hit ratio is α and memory access time is m?',
    options: ['α·m + (1−α)·2m', 'α·2m + (1−α)·m', 'm + α', '2m − α·m'],
    correctAnswer: 0,
    category: 'Memory Management',
    difficulty: 'Hard',
    explanation: 'On a TLB hit (prob α) we do 1 memory access; on a miss we do 2. EAT = α·m + (1−α)·2m.',
  },
  {
    id: 15,
    text: 'Which of the following is NOT a valid page-table structure?',
    options: ['Hierarchical page table', 'Hashed page table', 'Inverted page table', 'Circular page table'],
    correctAnswer: 3,
    category: 'Memory Management',
    difficulty: 'Medium',
    explanation: '"Circular page table" is not a standard structure. Common types are hierarchical, hashed, and inverted.',
  },
  {
    id: 16,
    text: 'Segmentation provides protection by:',
    options: [
      'Giving each segment a fixed size',
      'Associating base-limit pairs and permission bits with each segment',
      'Copying segments to the TLB',
      'Disabling virtual addressing',
    ],
    correctAnswer: 1,
    category: 'Memory Management',
    difficulty: 'Hard',
    explanation: 'Each segment descriptor holds a base address, limit, and r/w/x permission bits checked on every access.',
  },

  // ── PAGE REPLACEMENT ────────────────────────────────────────
  {
    id: 17,
    text: "Bélády's Anomaly states that increasing the number of frames can:",
    options: [
      'Always reduce page faults',
      'Increase page faults for certain algorithms',
      'Have no effect on page faults',
      'Only affect the LRU algorithm',
    ],
    correctAnswer: 1,
    category: 'Page Replacement',
    difficulty: 'Medium',
    explanation: "Bélády's Anomaly is observed in FIFO: more frames can sometimes cause MORE page faults.",
  },
  {
    id: 18,
    text: 'Which page-replacement algorithm is theoretically optimal (minimum page faults)?',
    options: ['LRU', 'FIFO', 'Optimal (OPT / Bélády)', 'Clock'],
    correctAnswer: 2,
    category: 'Page Replacement',
    difficulty: 'Easy',
    explanation: 'OPT replaces the page that will not be used for the longest future time — optimal but unrealisable in practice.',
  },
  {
    id: 19,
    text: 'The Clock (Second-Chance) algorithm is an approximation of which algorithm?',
    options: ['FIFO', 'LRU', 'MFU', 'OPT'],
    correctAnswer: 1,
    category: 'Page Replacement',
    difficulty: 'Medium',
    explanation: 'Clock gives pages a "second chance" using a reference bit, approximating LRU with lower overhead.',
  },
  {
    id: 20,
    text: 'In LRU page replacement, which data structure provides O(1) page replacement?',
    options: ['Stack', 'Queue', 'HashMap + Doubly Linked List', 'Binary Search Tree'],
    correctAnswer: 2,
    category: 'Page Replacement',
    difficulty: 'Hard',
    explanation: 'A HashMap gives O(1) lookup; a Doubly Linked List gives O(1) move-to-front. Together they implement O(1) LRU.',
  },
  {
    id: 21,
    text: 'Which algorithm replaces the page used MOST recently?',
    options: ['LRU', 'MRU (Most Recently Used)', 'LFU', 'FIFO'],
    correctAnswer: 1,
    category: 'Page Replacement',
    difficulty: 'Easy',
    explanation: 'MRU evicts the page accessed most recently — useful when recent pages are unlikely to be reused soon.',
  },
  {
    id: 22,
    text: 'Thrashing occurs when:',
    options: [
      'The CPU runs at 100% utilisation with no I/O',
      'Processes spend more time paging than executing',
      'The TLB hit ratio drops below 50%',
      'More processes are created than CPUs available',
    ],
    correctAnswer: 1,
    category: 'Page Replacement',
    difficulty: 'Medium',
    explanation: 'Thrashing: too many processes with too few frames cause constant page faults, collapsing CPU utilisation.',
  },

  // ── DEADLOCKS ───────────────────────────────────────────────
  {
    id: 23,
    text: 'Which of the following is NOT a necessary condition for deadlock?',
    options: ['Mutual Exclusion', 'Hold and Wait', 'Preemption', 'Circular Wait'],
    correctAnswer: 2,
    category: 'Deadlocks',
    difficulty: 'Easy',
    explanation: 'The four necessary conditions (Coffman) are: Mutual Exclusion, Hold-and-Wait, No Preemption, Circular Wait.',
  },
  {
    id: 24,
    text: "The Banker's Algorithm is used for deadlock:",
    options: ['Detection', 'Prevention', 'Avoidance', 'Recovery'],
    correctAnswer: 2,
    category: 'Deadlocks',
    difficulty: 'Easy',
    explanation: "The Banker's Algorithm checks if granting a resource request leads to a safe state — that's avoidance.",
  },
  {
    id: 25,
    text: 'A Resource Allocation Graph (RAG) with NO cycle means:',
    options: [
      'Deadlock is certain',
      'No deadlock is possible',
      'Deadlock may exist',
      'The system has reached a safe state',
    ],
    correctAnswer: 1,
    category: 'Deadlocks',
    difficulty: 'Medium',
    explanation: 'For single-instance resources, a cycle ↔ deadlock. No cycle → definitely no deadlock.',
  },
  {
    id: 26,
    text: 'Which deadlock prevention strategy breaks the "Hold and Wait" condition?',
    options: [
      'Allow preemption of held resources',
      'Force processes to request ALL resources at once before starting',
      'Impose a total ordering on resource types',
      'Limit the number of processes',
    ],
    correctAnswer: 1,
    category: 'Deadlocks',
    difficulty: 'Medium',
    explanation: 'Requiring all resources upfront before execution eliminates the possibility of holding some while waiting for others.',
  },
  {
    id: 27,
    text: "In the Banker's Algorithm, a state is 'safe' if:",
    options: [
      'No process is waiting',
      'There exists a safe sequence in which all processes can finish',
      'All resources are allocated',
      'The available vector is non-zero',
    ],
    correctAnswer: 1,
    category: 'Deadlocks',
    difficulty: 'Hard',
    explanation: 'A safe state guarantees at least one execution order (safe sequence) that lets every process complete.',
  },
  {
    id: 28,
    text: 'Circular Wait is prevented by:',
    options: [
      'Releasing all resources before requesting new ones',
      'Imposing a strict total ordering on resource types and requiring requests in that order',
      'Limiting each process to one resource',
      'Using semaphores',
    ],
    correctAnswer: 1,
    category: 'Deadlocks',
    difficulty: 'Hard',
    explanation: 'A global numbering of resource types forces processes to always request in increasing order, breaking circular chains.',
  },

  // ── PROCESS SYNCHRONIZATION ─────────────────────────────────
  {
    id: 29,
    text: 'A race condition occurs when:',
    options: [
      'Two processes run on two different CPUs simultaneously',
      'The outcome depends on the relative timing of concurrent accesses to shared data',
      'A process misses its scheduling quantum',
      'Memory pages are swapped faster than they are used',
    ],
    correctAnswer: 1,
    category: 'Process Synchronization',
    difficulty: 'Easy',
    explanation: 'A race condition: concurrent reads/writes to shared state produce non-deterministic results based on execution order.',
  },
  {
    id: 30,
    text: 'A binary semaphore can take values:',
    options: ['0 and 1 only', '0, 1, and 2', 'Any non-negative integer', 'Any integer'],
    correctAnswer: 0,
    category: 'Process Synchronization',
    difficulty: 'Easy',
    explanation: 'Binary semaphore ∈ {0, 1} — acts like a mutex lock. A counting semaphore can take any non-negative integer.',
  },
  {
    id: 31,
    text: 'The critical section problem requires which three properties?',
    options: [
      'Mutual Exclusion, Progress, Bounded Waiting',
      'Synchronisation, Atomicity, Fairness',
      'Locking, Unlocking, Safety',
      'Preemption, Starvation-free, Deadlock-free',
    ],
    correctAnswer: 0,
    category: 'Process Synchronization',
    difficulty: 'Medium',
    explanation: 'Mutual Exclusion (only one in CS at a time), Progress (decision is not postponed indefinitely), Bounded Waiting (limit on re-entry).',
  },
  {
    id: 32,
    text: 'Peterson\'s solution is designed for how many processes?',
    options: ['Any number', 'Two', 'Four', 'Must equal number of CPUs'],
    correctAnswer: 1,
    category: 'Process Synchronization',
    difficulty: 'Medium',
    explanation: "Peterson's classic solution handles exactly two processes using a turn variable and a flag array.",
  },
  {
    id: 33,
    text: 'A monitor differs from a semaphore in that:',
    options: [
      'Monitors are faster',
      'Monitors encapsulate shared data and synchronization inside a high-level construct',
      'Monitors allow multiple processes in the critical section',
      'Monitors work only with threads, not processes',
    ],
    correctAnswer: 1,
    category: 'Process Synchronization',
    difficulty: 'Hard',
    explanation: 'A monitor bundles shared variables and procedures; mutual exclusion is enforced automatically by the compiler/runtime.',
  },
  {
    id: 34,
    text: 'In the Producer–Consumer problem, what does the semaphore "full" represent?',
    options: [
      'Number of empty slots in the buffer',
      'Number of filled slots in the buffer',
      'Whether the buffer is completely full',
      'Number of waiting consumers',
    ],
    correctAnswer: 1,
    category: 'Process Synchronization',
    difficulty: 'Hard',
    explanation: '"full" counts items available for consumers; "empty" counts slots available for producers.',
  },

  // ── FILE SYSTEMS ─────────────────────────────────────────────
  {
    id: 35,
    text: 'An inode in a Unix file system stores:',
    options: [
      'The file name and its data',
      'File metadata (size, permissions, timestamps) and pointers to data blocks',
      'Only the file name',
      'Directory entries',
    ],
    correctAnswer: 1,
    category: 'File Systems',
    difficulty: 'Easy',
    explanation: 'An inode holds all file metadata except the name. The file name → inode mapping lives in the directory entry.',
  },
  {
    id: 36,
    text: 'Which disk allocation method causes external fragmentation?',
    options: ['Indexed allocation', 'Contiguous allocation', 'Linked allocation', 'FAT (File Allocation Table)'],
    correctAnswer: 1,
    category: 'File Systems',
    difficulty: 'Easy',
    explanation: 'Contiguous allocation requires a continuous run of blocks; over time, free blocks scatter causing external fragmentation.',
  },
  {
    id: 37,
    text: 'A hard link in Unix:',
    options: [
      'Creates a new copy of the file data',
      'Creates another directory entry pointing to the same inode',
      'Points to a path string (symbolic link)',
      'Locks the file for exclusive access',
    ],
    correctAnswer: 1,
    category: 'File Systems',
    difficulty: 'Medium',
    explanation: 'A hard link is simply another name (directory entry) for the same inode. The file data is shared; unlink only removes a name.',
  },
  {
    id: 38,
    text: 'In a Unix file system with 12 direct, 1 single-indirect, 1 double-indirect, and 1 triple-indirect block pointer, with block size 4KB and pointer size 4B, what is the maximum file size (approx.)?',
    options: ['~4 GB', '~64 GB', '~16 TB', '~4 TB'],
    correctAnswer: 2,
    category: 'File Systems',
    difficulty: 'Hard',
    explanation: 'Pointers per block = 4KB/4B = 1024. Triple-indirect covers 1024³ blocks × 4KB ≈ 4 TB (add direct+single+double for ~4 TB total).',
  },
  {
    id: 39,
    text: 'Journaling in a file system is used to:',
    options: [
      'Compress file data',
      'Maintain a log of changes to recover consistency after a crash',
      'Encrypt files on disk',
      'Speed up random reads',
    ],
    correctAnswer: 1,
    category: 'File Systems',
    difficulty: 'Medium',
    explanation: 'A journal records pending changes before committing them; on crash, the journal is replayed to restore consistency.',
  },

  // ── THREADS & CONCURRENCY ────────────────────────────────────
  {
    id: 40,
    text: 'Which resources are shared between threads of the same process?',
    options: [
      'Stack and registers',
      'Code segment, data segment, and open file descriptors',
      'Program counter and stack pointer',
      'Each thread has completely independent resources',
    ],
    correctAnswer: 1,
    category: 'Threads & Concurrency',
    difficulty: 'Easy',
    explanation: 'Threads share the process address space (code + data + heap + open files) but have their own stack and registers.',
  },
  {
    id: 41,
    text: 'User-level threads are managed by:',
    options: ['Kernel', 'A user-space thread library', 'Hardware', 'The CPU scheduler'],
    correctAnswer: 1,
    category: 'Threads & Concurrency',
    difficulty: 'Easy',
    explanation: 'User-level threads are created/scheduled by a library (e.g., POSIX pthreads with green threads) without kernel involvement.',
  },
  {
    id: 42,
    text: 'In the Many-to-One threading model, a blocking system call by one thread:',
    options: [
      'Only blocks that thread',
      'Blocks the entire process',
      'Triggers a context switch to another user thread',
      'Is handled asynchronously',
    ],
    correctAnswer: 1,
    category: 'Threads & Concurrency',
    difficulty: 'Medium',
    explanation: 'In Many-to-One, all user threads map to a single kernel thread, so one blocking call blocks all threads in that process.',
  },
  {
    id: 43,
    text: 'Which threading model allows true parallelism on multi-core systems?',
    options: ['Many-to-One', 'One-to-One', 'Many-to-Many (with ≥2 kernel threads)', 'Both B and C'],
    correctAnswer: 3,
    category: 'Threads & Concurrency',
    difficulty: 'Hard',
    explanation: 'One-to-One and Many-to-Many (with enough kernel threads) can run threads in parallel on separate cores.',
  },
  {
    id: 44,
    text: 'A spinlock is most appropriate when:',
    options: [
      'Waiting time is expected to be long',
      'The critical section is very short and contention is low',
      'The system has only one CPU',
      'Processes (not threads) share the lock',
    ],
    correctAnswer: 1,
    category: 'Threads & Concurrency',
    difficulty: 'Hard',
    explanation: 'Spinlocks busy-wait without sleeping; efficient only when the expected wait < context-switch overhead (very short critical sections).',
  },

  // ── VIRTUAL MEMORY ───────────────────────────────────────────
  {
    id: 45,
    text: 'Demand paging loads pages:',
    options: [
      'All at process start',
      'Only when referenced for the first time',
      'Based on a prefetch prediction algorithm',
      'In round-robin order',
    ],
    correctAnswer: 1,
    category: 'Virtual Memory',
    difficulty: 'Easy',
    explanation: 'Demand paging defers loading a page until the process actually references it, reducing startup time.',
  },
  {
    id: 46,
    text: 'A page fault occurs when:',
    options: [
      'A page is found in the TLB',
      'A page is not present in physical memory and must be loaded from disk',
      'Two pages map to the same frame',
      'The TLB is full',
    ],
    correctAnswer: 1,
    category: 'Virtual Memory',
    difficulty: 'Easy',
    explanation: 'Page fault: the valid bit in the page table entry is 0, so the OS must fetch the page from secondary storage.',
  },
  {
    id: 47,
    text: 'The working set model helps prevent thrashing by:',
    options: [
      'Limiting page table size',
      'Keeping only the active pages (working set) in memory and suspending processes that need more',
      'Increasing the time quantum',
      'Disabling virtual memory during peak load',
    ],
    correctAnswer: 1,
    category: 'Virtual Memory',
    difficulty: 'Medium',
    explanation: 'The working set (pages referenced in the last Δ time units) must fit in memory; if not, the process is suspended to free frames.',
  },
  {
    id: 48,
    text: 'Copy-on-Write (COW) in virtual memory means:',
    options: [
      'Both parent and child share the same physical pages until one writes, then a private copy is made',
      'The child always gets a full copy immediately on fork()',
      'Writes are buffered and never immediately committed',
      'The OS copies all pages on every context switch',
    ],
    correctAnswer: 0,
    category: 'Virtual Memory',
    difficulty: 'Medium',
    explanation: 'COW lets fork() share physical pages read-only; only on the first write to a shared page does the OS duplicate that page.',
  },
  {
    id: 49,
    text: 'Memory-mapped files allow:',
    options: [
      'Files to be stored in CPU registers',
      'File I/O to be performed via ordinary memory reads/writes in virtual address space',
      'Locking file pages in physical memory permanently',
      'Only read access to files through virtual memory',
    ],
    correctAnswer: 1,
    category: 'Virtual Memory',
    difficulty: 'Hard',
    explanation: 'mmap() maps a file region into virtual address space; reads/writes translate to file I/O through the page fault mechanism.',
  },
  {
    id: 50,
    text: 'Page sharing via the page table allows:',
    options: [
      'Two page table entries pointing to the same physical frame',
      'Two frames to hold the same virtual page',
      'The TLB to skip the page table',
      'Processes to see each other\'s private memory',
    ],
    correctAnswer: 0,
    category: 'Virtual Memory',
    difficulty: 'Hard',
    explanation: 'Shared libraries (e.g., libc) are mapped into multiple processes by pointing different virtual pages to the same physical frame.',
  },
];
